language: c
dist: xenial
cache: ccache
services:
  - docker

env:
  global:
    - ARCH=powerpc

matrix:
  include:
    # Ubuntu 20.04 GCC 9.3.0
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64le IMAGE=ubuntu-20.04 DEFCONFIG=ppc64le_defconfig
      name: "Ubuntu 20.04 kernel: ppc64le (PPC_BOOK3S_64 && LITTLE_ENDIAN)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=ppc64_defconfig
      name: "Ubuntu 20.04 kernel: ppc64 (PPC_BOOK3S_64 && BIG_ENDIAN)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=corenet64_smp_defconfig
      name: "Ubuntu 20.04 kernel: corenet64_smp (PPC_BOOK3E_64)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=pmac32_defconfig
      name: "Ubuntu 20.04 kernel: pmac32 (PPC_BOOK3S_32)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=ppc40x_defconfig
      name: "Ubuntu 20.04 kernel: ppc40x (PPC_40x)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=ppc44x_defconfig
      name: "Ubuntu 20.04 kernel: ppc44x (PPC_44x)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=mpc885_ads_defconfig
      name: "Ubuntu 20.04 kernel: mpc885_ads (PPC_8xx)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=corenet32_smp_defconfig
      name: "Ubuntu 20.04 kernel: corenet32_smp (PPC_85xx)"

    # kernel.org GCC 4.9.4 - BE only
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=korg-4.9.4 DEFCONFIG=ppc64_defconfig
      name: "GCC 4.9.4 kernel: ppc64 (PPC_BOOK3S_64 && BIG_ENDIAN)"

    # Selftests
    - os:   linux
      arch: ppc64le
      env:  TARGET=ppctests SUBARCH=ppc64le IMAGE=ubuntu-20.04
      name: "ppctests: ppc64le Ubuntu 20.04"
    - os:   linux
      arch: ppc64le
      env:  TARGET=ppctests SUBARCH=ppc64le IMAGE=ubuntu-16.04
      name: "ppctests: ppc64le Ubuntu 16.04"
    - os:   linux
      arch: amd64
      env:  TARGET=ppctests SUBARCH=ppc64 IMAGE=ubuntu-20.04
      name: "ppctests: ppc64 Ubuntu 20.04"
    - os:   linux
      arch: amd64
      env:  TARGET=ppctests SUBARCH=ppc64 IMAGE=ubuntu-16.04
      name: "ppctests: ppc64 Ubuntu 16.04"
    - os:   linux
      arch: ppc64le
      env:  TARGET=selftests SUBARCH=ppc64le IMAGE=ubuntu-20.04
      name: "selftests: ppc64le"
    - os:   linux
      arch: amd64
      env:  TARGET=selftests SUBARCH=ppc64 IMAGE=ubuntu-20.04
      name: "selftests: ppc64"

install:
  - docker pull linuxppc/build:$IMAGE-$(uname -m)

script:
  - mkdir -p $HOME/.ccache
  - travis_wait 50 ./arch/powerpc/tools/ci-build.sh
